<?php

// FIXME: Currently this module only functions correctly when:
//        1) Comment threading is DISABLED for the node type
//        2) Comments ordering is OLDEST --> NEWEST

/**
 * Implements hook_preprocess_comment_wrapper().
 */
function revision_comment_marker_preprocess_comment_wrapper(&$variables) {
  $node     = $variables['node'];
  $comments = &$variables['content']['comments'];

  $result = db_query("SELECT vid, timestamp
                        FROM {node_revision}
                       WHERE nid = :nid
                    ORDER BY vid ASC", array(':nid' => $node->nid));

  $revisions = array();
  $version   = 1;

  foreach ($result as $record) {
    $record->version = ($version++);
    $revisions[] = $record;
  }

  $revision = array_shift($revisions);

  foreach (element_children($comments) as $key) {
    if (!is_numeric($key)) {
      continue;
    }

    $comment = &$comments[$key];

    while ($revision && $revision->timestamp < $comment['#comment']->created) {
      revision_comment_marker_inject_marker($node, $revision, $comment);
      $revision = array_shift($revisions);
    }
  }

  if ($comments && $revision) {
    $last_comment = array();
    revision_comment_marker_inject_marker($node, $revision, $last_comment);
    $comments[] = $last_comment;
  }
}

/**
 * Adds a marker above a comment to indicate that a revision occurred before
 * this comment was posted.
 */
function revision_comment_marker_inject_marker($node, $revision, &$comment) {
  if (!isset($comment['revision_comment_marker'])) {
    $comment['revision_comment_marker'] = array(
      '#weight' => -100,
    );
  }

  $comment['revision_comment_marker'][$revision->version] = array(
    '#markup' => '<div id="revision-comment-marker-' . $revision->version . '" class="revision-comment-marker">' .
                   l(
                     '<span class="version-label">' . t('Version') . '</span> ' .
                     '<span class="version-number">' . $revision->version . '</span> ',
                     "node/$node->nid/revisions/$revision->vid",
                     array('html' => TRUE)
                    ) .
                 '</div>'
  );
}